//! Venue-conformant LaTeX source.
//!
//! This is the mechanical half. It sets the document class the venue
//! demands, writes an anonymous author block when the venue is
//! double-blind, and stubs in any section the venue requires that the
//! draft does not have.
//!
//! It converts a deliberately small subset of markdown. Anything it does
//! not understand is copied through inside a marked block rather than
//! guessed at, because a table silently mangled into the wrong number of
//! columns is worse than one the author is told to convert. It also does
//! not render: producing a PDF is a separate job with a separate
//! toolchain.
//!
//! It anonymises the author block and nothing else. It will not quietly
//! scrub identity out of the body, because that would remove the evidence
//! the conformance report is pointing at.

use crate::manuscript::Manuscript;
use crate::profile::{CheckKind, VenueProfile};

/// Emit a manuscript for `profile` from `manuscript`.
pub fn emit(manuscript: &Manuscript, profile: &VenueProfile) -> String {
    let anonymous = profile
        .rules
        .iter()
        .any(|r| r.check == CheckKind::Anonymity);
    let mut out = String::new();

    out.push_str(&format!(
        "% Generated by zorp-agent conform for {} ({}).\n",
        profile.name, profile.id
    ));
    out.push_str(&format!(
        "% Venue requirements as last checked on {}.\n",
        profile.checked
    ));
    out.push_str("% Sources for those requirements:\n");
    for rule in &profile.rules {
        match &rule.source {
            Some(source) => out.push_str(&format!("%   {}: {source}\n", rule.id)),
            None => out.push_str(&format!(
                "%   {}: NO SOURCE, this requirement is unverified\n",
                rule.id
            )),
        }
    }
    out.push_str(
        "%\n% The author block below is anonymised where the venue is double-blind.\n\
         % Body text is copied as written: this file does not scrub identity out\n\
         % of the prose, because that would hide what the conformance report is\n\
         % pointing at. Fix the leaks it lists in the draft, not here.\n\n",
    );

    match &preamble_of(profile) {
        Some(preamble) => out.push_str(preamble),
        None => out.push_str(
            "% This profile names no document class. Add a `template` rule to it,\n\
             % or paste the venue's own preamble here.\n\\documentclass{article}",
        ),
    }
    out.push_str("\n\n");

    let title = manuscript
        .front_matter
        .title
        .as_ref()
        .map(|t| escape(&t.value))
        .unwrap_or_else(|| "% TODO: the draft has no title".to_string());
    out.push_str(&format!("\\title{{{title}}}\n"));

    if anonymous {
        out.push_str(
            "% This venue is double-blind, so the author block is a placeholder.\n\
             \\author{Anonymous Author(s) \\\\ Paper under double-blind review}\n",
        );
    } else {
        let authors: Vec<String> = manuscript
            .front_matter
            .authors
            .iter()
            .map(|a| escape(&a.value))
            .collect();
        if authors.is_empty() {
            out.push_str("\\author{% TODO: the draft names no author\n}\n");
        } else {
            out.push_str(&format!("\\author{{{}}}\n", authors.join(" \\and ")));
        }
    }

    out.push_str("\n\\begin{document}\n\\maketitle\n\n");

    if let Some(abstract_text) = &manuscript.front_matter.abstract_text {
        out.push_str("\\begin{abstract}\n");
        out.push_str(&inline(&abstract_text.value));
        out.push_str("\n\\end{abstract}\n\n");
    }

    out.push_str(&body(manuscript));

    for stub in missing_section_stubs(manuscript, profile) {
        out.push_str(&stub);
    }

    out.push_str("\n\\end{document}\n");
    out
}

fn preamble_of(profile: &VenueProfile) -> Option<String> {
    profile
        .rules
        .iter()
        .find(|r| r.check == CheckKind::Template)
        .and_then(|r| r.documentclass.clone())
}

/// A `\section` stub for every section the venue requires and the draft
/// does not have. Emitted at the end with a comment, because this cannot
/// know where the argument wants it.
fn missing_section_stubs(manuscript: &Manuscript, profile: &VenueProfile) -> Vec<String> {
    let mut stubs = Vec::new();
    for rule in &profile.rules {
        if rule.check != CheckKind::RequiredSection {
            continue;
        }
        if manuscript.find_section(&rule.headings).is_some() {
            continue;
        }
        let Some(name) = rule.headings.first() else {
            continue;
        };
        let placement = rule
            .after
            .as_ref()
            .map(|a| format!(" It belongs after the {a} section."))
            .unwrap_or_default();
        stubs.push(format!(
            "\n% zorp-venue: {} requires this section and the draft has none.\n\
             % {}{placement}\n\\section{{{}}}\n% TODO: write this.\n",
            profile.name,
            rule.requirement,
            escape(name)
        ));
    }
    stubs
}

fn body(manuscript: &Manuscript) -> String {
    let mut out = String::new();
    let mut in_code = false;
    let mut in_table = false;
    let mut lines = manuscript
        .body_lines()
        .map(|(_, l)| l.to_string())
        .collect::<Vec<_>>()
        .into_iter()
        .peekable();

    while let Some(line) = lines.next() {
        let trimmed = line.trim_start();

        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            out.push_str(if in_code {
                "\\end{verbatim}\n"
            } else {
                "\\begin{verbatim}\n"
            });
            in_code = !in_code;
            continue;
        }
        if in_code {
            out.push_str(&line);
            out.push('\n');
            continue;
        }

        // Markdown pipe tables are copied through, marked. Guessing a
        // column spec and an alignment is how a table ends up silently
        // wrong in the PDF.
        if trimmed.starts_with('|') {
            if !in_table {
                out.push_str(
                    "\n% zorp-venue: markdown table below, not converted. Turn it into\n\
                     % a tabular by hand, or run the draft through a converter.\n\
                     \\begin{verbatim}\n",
                );
                in_table = true;
            }
            out.push_str(&line);
            out.push('\n');
            if !lines.peek().is_some_and(|n| n.trim_start().starts_with('|')) {
                out.push_str("\\end{verbatim}\n\n");
                in_table = false;
            }
            continue;
        }

        if trimmed.starts_with('#') {
            let level = trimmed.chars().take_while(|c| *c == '#').count();
            let title = trimmed[level..].trim().trim_end_matches('#').trim();
            let command = match level {
                1 => "section",
                2 => "subsection",
                _ => "subsubsection",
            };
            out.push_str(&format!("\n\\{command}{{{}}}\n\n", inline(title)));
            continue;
        }

        if let Some(item) = trimmed.strip_prefix("- ").or(trimmed.strip_prefix("* ")) {
            out.push_str(&format!("\\item {}\n", inline(item)));
            continue;
        }

        out.push_str(&inline(&line));
        out.push('\n');
    }
    if in_code || in_table {
        out.push_str("\\end{verbatim}\n");
    }
    out
}

/// Convert the inline markdown this understands and escape everything
/// else.
fn inline(text: &str) -> String {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < chars.len() {
        // Code span.
        if chars[i] == '`' {
            if let Some(end) = find_from(&chars, i + 1, '`') {
                let inner: String = chars[i + 1..end].iter().collect();
                out.push_str(&format!("\\texttt{{{}}}", escape(&inner)));
                i = end + 1;
                continue;
            }
        }
        // Citation: [@a] or [@a; @b].
        if chars[i] == '[' && chars.get(i + 1) == Some(&'@') {
            if let Some(end) = find_from(&chars, i + 1, ']') {
                let inner: String = chars[i + 1..end].iter().collect();
                let keys: Vec<String> = inner
                    .split(';')
                    .filter_map(|k| k.trim().strip_prefix('@').map(str::to_string))
                    .collect();
                if !keys.is_empty() {
                    out.push_str(&format!("\\citep{{{}}}", keys.join(",")));
                    i = end + 1;
                    continue;
                }
            }
        }
        // Link: [text](url). Images are handled the same way, minus the
        // bang, so a figure comes through as a link with a comment.
        if chars[i] == '[' {
            if let Some(close) = find_from(&chars, i + 1, ']') {
                if chars.get(close + 1) == Some(&'(') {
                    if let Some(paren) = find_from(&chars, close + 2, ')') {
                        let label: String = chars[i + 1..close].iter().collect();
                        let url: String = chars[close + 2..paren].iter().collect();
                        out.push_str(&format!(
                            "\\href{{{}}}{{{}}}",
                            url.replace('%', "\\%"),
                            inline(&label)
                        ));
                        i = paren + 1;
                        continue;
                    }
                }
            }
        }
        if chars[i] == '*' && chars.get(i + 1) == Some(&'*') {
            if let Some(end) = find_pair(&chars, i + 2) {
                let inner: String = chars[i + 2..end].iter().collect();
                out.push_str(&format!("\\textbf{{{}}}", inline(&inner)));
                i = end + 2;
                continue;
            }
        }
        if chars[i] == '*' {
            if let Some(end) = find_from(&chars, i + 1, '*') {
                let inner: String = chars[i + 1..end].iter().collect();
                out.push_str(&format!("\\emph{{{}}}", inline(&inner)));
                i = end + 1;
                continue;
            }
        }
        out.push_str(&escape_char(chars[i]));
        i += 1;
    }
    out
}

fn find_from(chars: &[char], start: usize, target: char) -> Option<usize> {
    (start..chars.len()).find(|&i| chars[i] == target)
}

fn find_pair(chars: &[char], start: usize) -> Option<usize> {
    (start..chars.len().saturating_sub(1))
        .find(|&i| chars[i] == '*' && chars[i + 1] == '*')
}

fn escape(text: &str) -> String {
    text.chars().map(escape_char).collect()
}

fn escape_char(c: char) -> String {
    match c {
        '&' | '%' | '$' | '#' | '_' | '{' | '}' => format!("\\{c}"),
        '~' => "\\textasciitilde{}".to_string(),
        '^' => "\\textasciicircum{}".to_string(),
        '\\' => "\\textbackslash{}".to_string(),
        _ => c.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inline_converts_the_subset_and_escapes_the_rest() {
        assert_eq!(inline("**bold**"), "\\textbf{bold}");
        assert_eq!(inline("*em*"), "\\emph{em}");
        assert_eq!(inline("`code_x`"), "\\texttt{code\\_x}");
        assert_eq!(inline("see [@a; @b]"), "see \\citep{a,b}");
        assert_eq!(
            inline("[repo](https://example.test)"),
            "\\href{https://example.test}{repo}"
        );
        assert_eq!(inline("100% of a_b"), "100\\% of a\\_b");
    }
}
