mod error;

pub use error::CoWriteError;

use crate::agent::{Agent, Outcome};
use crate::sanitize::{sanitize, SanitizeMode};
use std::fmt::Write as _;
use zorp_track::checkpoint::CheckpointMode;
use zorp_track::experiment::MetricValue;
use zorp_track::track::TrackStatus;
use zorp_track::{Project, TrackError};

/// Collect every metric recorded across all of `track_id`'s experiments,
/// as `(experiment_id, metric_key, MetricValue)` triples, in experiment
/// order then metric order. One joined query, not one query per
/// experiment.
fn all_metrics(
    project: &Project,
    track_id: &str,
) -> Result<Vec<(String, String, MetricValue)>, TrackError> {
    project.store.metrics_for_track(track_id)
}

fn format_metric_value(value: &MetricValue) -> String {
    match value {
        MetricValue::Number(n) => n.to_string(),
        MetricValue::Text(s) => s.clone(),
        MetricValue::Bool(b) => b.to_string(),
    }
}

fn build_task_prompt(
    hypothesis: &str,
    project: &Project,
    track_id: &str,
    metrics: &[(String, String, MetricValue)],
) -> Result<String, TrackError> {
    let mut task = format!("Hypothesis: {hypothesis}\n\n");

    match project.store.get_validation(track_id) {
        Ok(v) => {
            let _ = write!(
                task,
                "Validation verdict: {}\nRedundancy: {:.0}/100. Feasibility: {:.0}/100.\n",
                v.verdict, v.redundancy_score, v.feasibility_score
            );
            for c in &v.redundancy_citations {
                let _ = writeln!(task, "- redundancy citation: \"{}\" ({})", c.text, c.source);
            }
            for c in &v.feasibility_citations {
                let _ = writeln!(
                    task,
                    "- feasibility citation: \"{}\" ({})",
                    c.text, c.source
                );
            }
            task.push('\n');
        }
        Err(TrackError::NotFound {
            kind: "validation", ..
        }) => {}
        Err(e) => return Err(e),
    }

    task.push_str("Recorded metrics:\n");
    for (experiment_id, key, value) in metrics {
        let _ = writeln!(
            task,
            "- [{experiment_id}] {key} = {}",
            format_metric_value(value)
        );
    }
    task.push_str("\nDraft a short evidence-based artifact (a decision memo or summary) based only on this data.");
    Ok(task)
}

/// Run co-write for an already-created track with at least one recorded
/// metric: draft an artifact grounded in the track's evidence, write it
/// to `draft.md`, and checkpoint it. Returns whether the checkpoint was
/// approved. Unlike `validate::run`/`investigate::run`, neither outcome
/// changes the track's status.
///
/// `sanitize_mode` decides how much of the text sanitization pass runs
/// over the draft before it is written. Whatever it changes is reported
/// on stderr and in the checkpoint prompt.
pub fn run(
    agent: &mut Agent,
    project: &Project,
    track_id: &str,
    hypothesis: &str,
    checkpoint_mode: &CheckpointMode,
    sanitize_mode: SanitizeMode,
) -> Result<bool, CoWriteError> {
    let track = project.store.get_track(track_id)?;
    if track.status == TrackStatus::Killed {
        return Err(CoWriteError::TrackKilled);
    }

    let metrics = all_metrics(project, track_id)?;
    if metrics.is_empty() {
        return Err(CoWriteError::NoMetrics);
    }

    let task = build_task_prompt(hypothesis, project, track_id, &metrics)?;
    let outcome = agent.run(&task);
    let raw = match outcome {
        Outcome::Complete(text) => text,
        other => return Err(CoWriteError::AgentOutcome(other.describe())),
    };

    let cleaned = sanitize(&raw, sanitize_mode);
    let draft = cleaned.text;
    let sanitize_note = cleaned.report.summary();
    if let Some(note) = &sanitize_note {
        eprintln!("zorp-agent: co-write sanitized the draft: {note}");
    }

    let track_dir = project.track_dir(track_id);
    std::fs::create_dir_all(&track_dir)?;
    let draft_path = track_dir.join("draft.md");

    if let Ok(meta) = std::fs::metadata(&draft_path) {
        if let Ok(modified) = meta.modified() {
            let mtime_millis = modified
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as i64)
                .unwrap_or(0);
            if let Some(last_checkpoint) =
                project.store.latest_checkpoint_time(track_id, "co-write")?
            {
                if mtime_millis > last_checkpoint {
                    eprintln!("zorp-agent: draft.md appears to have been edited since it was last generated by co-write");
                }
            }
        }
    }

    std::fs::write(&draft_path, &draft)?;

    let mut prompt = format!(
        "co-write: draft written to {} ({} lines, {} metrics",
        draft_path.display(),
        draft.lines().count(),
        metrics.len()
    );
    // The checkpoint is where a human decides on this draft, so it is
    // where they have to be told the text is not verbatim what the model
    // produced.
    if let Some(note) = &sanitize_note {
        let _ = write!(prompt, ", sanitized: {note}");
    }
    prompt.push_str("). Ready for review?");
    let approved =
        project
            .store
            .record_checkpoint(track_id, "co-write", checkpoint_mode, &prompt)?;

    Ok(approved)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AssistantMessage, Message, Model};
    use crate::BoxErr;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Arc;
    use tempfile::tempdir;
    use zorp_track::experiment::ExperimentStatus;

    struct StubModel {
        response: String,
        calls: Arc<AtomicUsize>,
    }

    impl Model for StubModel {
        fn complete(
            &self,
            _messages: &[Message],
            _tools: &[serde_json::Value],
        ) -> Result<AssistantMessage, BoxErr> {
            self.calls.fetch_add(1, Ordering::SeqCst);
            Ok(AssistantMessage {
                content: self.response.clone(),
                tool_calls: vec![],
                finish_reason: "stop".to_string(),
                reasoning_content: None,
            })
        }

        fn clone_box(&self) -> Box<dyn Model> {
            Box::new(StubModel {
                response: self.response.clone(),
                calls: self.calls.clone(),
            })
        }
    }

    fn build_agent(response: &str) -> Agent {
        let calls = Arc::new(AtomicUsize::new(0));
        let model = StubModel {
            response: response.to_string(),
            calls,
        };
        Agent::new(
            Box::new(model),
            "system",
            5,
            std::env::temp_dir(),
            crate::cancel_token(),
            crate::ApprovalMode::AutoApprove,
        )
        .register_builtins()
    }

    fn track_with_one_metric(project: &Project, track_id: &str) {
        project
            .store
            .create_track(track_id, "does caching help")
            .unwrap();
        let exp = project
            .store
            .create_experiment(track_id, "no-prereg")
            .unwrap();
        project
            .store
            .set_experiment_status(&exp.id, ExperimentStatus::Completed)
            .unwrap();
        project
            .store
            .record_metric(&exp.id, "latency_ms", MetricValue::Number(42.0))
            .unwrap();
    }

    #[test]
    fn killed_track_is_refused() {
        let mut agent = build_agent("a draft");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        project
            .store
            .set_track_status("t1", TrackStatus::Killed)
            .unwrap();
        let mode = CheckpointMode::terminal(true).unwrap();

        let err = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap_err();
        assert!(matches!(err, CoWriteError::TrackKilled));
    }

    #[test]
    fn no_metrics_is_refused() {
        let mut agent = build_agent("a draft");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        project
            .store
            .create_track("t1", "does caching help")
            .unwrap();
        let mode = CheckpointMode::terminal(true).unwrap();

        let err = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap_err();
        assert!(matches!(err, CoWriteError::NoMetrics));
    }

    #[test]
    fn full_run_writes_draft_and_checkpoints() {
        let mut agent = build_agent("Latency improved to 42ms.");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let mode = CheckpointMode::terminal(true).unwrap();

        let approved = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();
        assert!(approved);

        let draft_path = project.track_dir("t1").join("draft.md");
        let content = std::fs::read_to_string(&draft_path).unwrap();
        assert_eq!(content, "Latency improved to 42ms.");
    }

    #[test]
    fn rejected_checkpoint_does_not_kill_the_track() {
        let mut agent = build_agent("a draft");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let mode = CheckpointMode::Interactive(Arc::new(RejectAll));

        let approved = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();
        assert!(!approved);

        let track = project.store.get_track("t1").unwrap();
        assert_eq!(track.status, TrackStatus::Active);
    }

    struct RejectAll;
    impl zorp_track::checkpoint::Decider for RejectAll {
        fn decide(&self, _prompt: &str) -> bool {
            false
        }
    }

    /// Captures the prompt string it was handed so a test can assert on
    /// what the human would actually have been asked.
    struct CapturingDecider {
        prompt: std::sync::Mutex<Option<String>>,
    }

    impl zorp_track::checkpoint::Decider for CapturingDecider {
        fn decide(&self, prompt: &str) -> bool {
            *self.prompt.lock().unwrap() = Some(prompt.to_string());
            true
        }
    }

    /// A draft with one of everything: an invisible, a bidi override, a
    /// clause dash, curly quotes, an ellipsis, and a fenced code block
    /// that must come through untouched.
    const DIRTY_DRAFT: &str = "Latency\u{200B} improved \u{2014} \u{201C}a lot\u{201D}\u{2026}\u{202E}\n\n```\nlet s = \"a\u{2014}b\";\n```\n";
    const CLEAN_DRAFT: &str =
        "Latency improved, \"a lot\"...\n\n```\nlet s = \"a\u{2014}b\";\n```\n";

    #[test]
    fn the_draft_is_sanitized_before_it_is_written() {
        let mut agent = build_agent(DIRTY_DRAFT);
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let mode = CheckpointMode::terminal(true).unwrap();

        run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();

        let content = std::fs::read_to_string(project.track_dir("t1").join("draft.md")).unwrap();
        assert_eq!(content, CLEAN_DRAFT);
    }

    #[test]
    fn sanitize_off_writes_the_model_text_verbatim() {
        let mut agent = build_agent(DIRTY_DRAFT);
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let mode = CheckpointMode::terminal(true).unwrap();

        run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Off,
        )
        .unwrap();

        let content = std::fs::read_to_string(project.track_dir("t1").join("draft.md")).unwrap();
        assert_eq!(content, DIRTY_DRAFT);
    }

    #[test]
    fn the_checkpoint_prompt_says_what_sanitizing_changed() {
        let mut agent = build_agent(DIRTY_DRAFT);
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let decider = Arc::new(CapturingDecider {
            prompt: std::sync::Mutex::new(None),
        });
        let mode = CheckpointMode::Interactive(decider.clone());

        run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();

        let prompt = decider
            .prompt
            .lock()
            .unwrap()
            .clone()
            .expect("decider should have been asked");
        assert!(prompt.contains("sanitized:"), "{prompt}");
        assert!(prompt.contains("1 invisible removed"), "{prompt}");
        assert!(prompt.contains("1 bidi controls removed"), "{prompt}");
        assert!(prompt.contains("1 dashes normalized"), "{prompt}");
    }

    #[test]
    fn a_clean_draft_leaves_the_checkpoint_prompt_alone() {
        let mut agent = build_agent("Latency improved to 42ms.");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let decider = Arc::new(CapturingDecider {
            prompt: std::sync::Mutex::new(None),
        });
        let mode = CheckpointMode::Interactive(decider.clone());

        run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();

        let prompt = decider.prompt.lock().unwrap().clone().unwrap();
        assert!(!prompt.contains("sanitized"), "{prompt}");
    }

    #[test]
    fn existing_validation_is_included_without_breaking_the_run() {
        let mut agent = build_agent("Latency improved to 42ms.");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        project
            .store
            .record_validation("t1", 20.0, &[], 85.0, &[], "worth investigating")
            .unwrap();
        let mode = CheckpointMode::terminal(true).unwrap();

        let approved = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();
        assert!(approved);

        let draft_path = project.track_dir("t1").join("draft.md");
        let content = std::fs::read_to_string(&draft_path).unwrap();
        assert_eq!(content, "Latency improved to 42ms.");
    }

    #[test]
    fn task_prompt_carries_validation_citations() {
        use zorp_track::validation::Citation;
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let red = vec![Citation {
            text: "no prior benchmark found".into(),
            source: "search result 1".into(),
        }];
        let feas = vec![Citation {
            text: "a harness already exists".into(),
            source: "repo README".into(),
        }];
        project
            .store
            .record_validation("t1", 20.0, &red, 85.0, &feas, "worth investigating")
            .unwrap();

        let metrics = all_metrics(&project, "t1").unwrap();
        let task = build_task_prompt("does caching help", &project, "t1", &metrics).unwrap();

        assert!(
            task.contains("- redundancy citation: \"no prior benchmark found\" (search result 1)"),
            "{task}"
        );
        assert!(
            task.contains("- feasibility citation: \"a harness already exists\" (repo README)"),
            "{task}"
        );
    }

    #[test]
    fn second_run_overwrites_draft_even_if_mtime_warning_would_fire() {
        let mut agent = build_agent("first draft");
        let dir = tempdir().unwrap();
        let project = Project::open(dir.path()).unwrap();
        track_with_one_metric(&project, "t1");
        let mode = CheckpointMode::terminal(true).unwrap();

        let approved = run(
            &mut agent,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();
        assert!(approved);

        let draft_path = project.track_dir("t1").join("draft.md");
        let content = std::fs::read_to_string(&draft_path).unwrap();
        assert_eq!(content, "first draft");

        // Simulate a hand-edit landing after the first run's checkpoint, so
        // draft.md's mtime is strictly later than the latest co-write
        // checkpoint. That is exactly the condition the mtime warning
        // checks. The warning must be advisory only: the second run still
        // succeeds and still overwrites the file.
        std::thread::sleep(std::time::Duration::from_millis(20));
        std::fs::write(&draft_path, "HUMAN EDIT").unwrap();

        let mut agent2 = build_agent("second draft");
        let approved2 = run(
            &mut agent2,
            &project,
            "t1",
            "does caching help",
            &mode,
            SanitizeMode::Full,
        )
        .unwrap();
        assert!(approved2);

        let content2 = std::fs::read_to_string(&draft_path).unwrap();
        assert_eq!(content2, "second draft");
    }
}
