"""Generate the figures used in zorp-paper.md.

Re-run with `python3 make_figures.py` from this directory whenever the
architecture or test counts change. Every figure is built from real repo
state (crate layout, spec text, `cargo test` output), not illustrative
mockups.

Typography matches the paper body (Times via newtx in LaTeX, Times New
Roman here) so figures do not read as pasted in from a different
document. Colors are zorp-landing's palette
(zorp-landing/src/styles/tokens.css), used sparingly: navy for
structure, blue only as an accent.

figures/logo.png is NOT generated by this script. It is the real zorp
mark, placed directly. Do not overwrite it.
"""

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Circle

OUT = os.path.join(os.path.dirname(__file__), "figures")
os.makedirs(OUT, exist_ok=True)

# zorp-landing/src/styles/tokens.css
NAVY = "#12182B"     # --z-fg
BLUE = "#1450F5"     # --z-accent
TINT = "#8FB0FB"     # --z-tint
MUTED = "#5B6478"    # --z-muted
BORDER = "#DDE1E9"   # --z-border
SURFACE = "#F6F8FB"  # --z-surface

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "STIXGeneral", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "text.color": NAVY,
    "axes.labelcolor": NAVY,
    "xtick.color": NAVY,
    "ytick.color": NAVY,
    "axes.edgecolor": MUTED,
    "figure.facecolor": "white",
    "savefig.facecolor": "white",
    "savefig.dpi": 400,
})

# The paper's text block is 5.5in wide (letterpaper, 1.5in side margins).
TEXTWIDTH = 5.5


def box(ax, x, y, w, h, text, fc=SURFACE, ec=MUTED, fontsize=8.5,
        textcolor=NAVY, lw=0.9, weight="normal"):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.015,rounding_size=0.05",
        fc=fc, ec=ec, lw=lw, mutation_aspect=1,
    ))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
            color=textcolor, fontsize=fontsize, fontweight=weight,
            linespacing=1.35)


def arrow(ax, x0, y0, x1, y1, color=MUTED, lw=0.9, style="-|>"):
    ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                arrowprops=dict(arrowstyle=style, color=color, lw=lw,
                                shrinkA=0, shrinkB=0))


# ---------------------------------------------------------------------------
# Figure 1: layered architecture, from docs/superpowers/specs/
# 2026-08-09-zorp-architecture-design.md ("Structure").
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(TEXTWIDTH, 3.1))
ax.set_xlim(0, 10)
ax.set_ylim(0, 6.6)
ax.axis("off")

box(ax, 0.2, 5.35, 9.6, 0.85,
    "zorp-agent  (one binary, one CLI)",
    fc=NAVY, ec=NAVY, textcolor="white", fontsize=9.5, weight="bold")

caps = ["validate", "investigate", "co-write", "deliver"]
cw = (9.6 - 3 * 0.18) / 4
for i, c in enumerate(caps):
    box(ax, 0.2 + i * (cw + 0.18), 4.05, cw, 0.85, c,
        fc="white", ec=BLUE, fontsize=9, textcolor=BLUE)

box(ax, 0.2, 2.65, 9.6, 1.0,
    "zorp-track  (shared foundation, feature-gated)\n"
    "tracks $\\cdot$ evidence record (DuckDB) $\\cdot$ library (LanceDB) $\\cdot$ checkpoints",
    fc=SURFACE, ec=TINT)

box(ax, 0.2, 1.35, 9.6, 1.0,
    "zorp-agent harness  (inherited)\n"
    "tools $\\cdot$ sandbox $\\cdot$ trust $\\cdot$ verification $\\cdot$ sessions $\\cdot$ MCP",
    fc=SURFACE, ec=BORDER)

box(ax, 0.2, 0.25, 9.6, 0.8,
    "zorp core  (model transport, raw primitives)",
    fc=SURFACE, ec=BORDER)

for y_top, y_bot in [(5.35, 4.90), (4.05, 3.65), (2.65, 2.35), (1.35, 1.05)]:
    arrow(ax, 5, y_top, 5, y_bot)

fig.savefig(os.path.join(OUT, "architecture.png"), bbox_inches="tight",
            pad_inches=0.02)
plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 2: the four capabilities as a checkpointed sequence, from
# docs/ARCHITECTURE.md and the per-capability specs. Detail lives in the
# caption and body text, not crammed into the boxes.
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(TEXTWIDTH, 1.95))
ax.set_xlim(0, 13.7)
ax.set_ylim(0, 4.6)
ax.axis("off")

stages = [
    ("validate", "is the question\nworth pursuing?"),
    ("investigate", "gather evidence,\nevery attempt kept"),
    ("co-write", "draft from the\nevidence record"),
    ("deliver", "match it to\nthe right venue"),
]
w, h, gap = 2.72, 1.55, 0.55
x0, y0 = 0.15, 1.35

for i, (name, desc) in enumerate(stages):
    x = x0 + i * (w + gap)
    cx = x + w / 2
    box(ax, x, y0, w, h, "", fc="white", ec=BLUE, lw=1.0)
    ax.text(cx, y0 + h - 0.44, name, ha="center", va="center",
            fontsize=9.5, color=BLUE, fontweight="bold")
    ax.text(cx, y0 + 0.44, desc, ha="center", va="center",
            fontsize=7.8, color=MUTED, linespacing=1.4)

    # checkpoint marker on the arrow leaving each stage
    if i < len(stages) - 1:
        mx = x + w + gap / 2
        arrow(ax, x + w + 0.06, y0 + h / 2, mx - 0.16, y0 + h / 2)
        arrow(ax, mx + 0.16, y0 + h / 2, x + w + gap - 0.06, y0 + h / 2)
        ax.add_patch(Circle((mx, y0 + h / 2), 0.155, fc="white", ec=NAVY,
                            lw=0.9, zorder=3))
        ax.plot([mx - 0.07, mx - 0.02, mx + 0.075],
                [y0 + h / 2, y0 + h / 2 - 0.055, y0 + h / 2 + 0.07],
                color=NAVY, lw=0.9, zorder=4,
                solid_capstyle="round", solid_joinstyle="round")

# final checkpoint after deliver
fx = x0 + 4 * (w + gap) - gap
arrow(ax, fx + 0.06, y0 + h / 2, fx + 0.42, y0 + h / 2)
ax.add_patch(Circle((fx + 0.62, y0 + h / 2), 0.155, fc="white", ec=NAVY,
                    lw=0.9, zorder=3))
ax.plot([fx + 0.55, fx + 0.60, fx + 0.695],
        [y0 + h / 2, y0 + h / 2 - 0.055, y0 + h / 2 + 0.07],
        color=NAVY, lw=0.9, zorder=4,
        solid_capstyle="round", solid_joinstyle="round")

ax.text(6.42, 3.72, "human checkpoint", ha="center", va="center",
        fontsize=7.8, color=NAVY, style="italic")
arrow(ax, 5.15, 3.62, 3.145, 2.36, color=NAVY, lw=0.7)
arrow(ax, 7.70, 3.62, 9.685, 2.36, color=NAVY, lw=0.7)

ax.text(6.42, 0.52, "each capability also runs standalone",
        ha="center", va="center", fontsize=7.8, color=MUTED, style="italic")

fig.savefig(os.path.join(OUT, "pipeline.png"), bbox_inches="tight",
            pad_inches=0.02)
plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 3: test counts per crate, from `cargo test -p <crate>` at default
# features plus `cargo test -p zorp-agent --features research`, on
# 2026-08-13 at HEAD fd07e81. `cargo test --workspace` totals 538.
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(TEXTWIDTH, 2.3))

crates = ["zorp\n(core)", "zorp-mcp", "zorp-eval", "zorp-track",
          "zorp-agent", "zorp-agent\n(+research)"]
counts = [24, 23, 41, 69, 381, 445]
colors = [TINT, TINT, TINT, TINT, BLUE, BLUE]

bars = ax.bar(crates, counts, color=colors, edgecolor=NAVY, linewidth=0.7,
              width=0.62)
for b, c in zip(bars, counts):
    ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 9, str(c),
            ha="center", va="bottom", fontsize=8, color=NAVY)

ax.set_ylabel("passing tests", fontsize=8.5)
ax.tick_params(axis="both", labelsize=8, length=3)
ax.spines[["top", "right"]].set_visible(False)
ax.spines[["left", "bottom"]].set_linewidth(0.7)
ax.set_ylim(0, max(counts) * 1.16)
ax.set_axisbelow(True)
ax.grid(axis="y", color=BORDER, lw=0.6)

fig.savefig(os.path.join(OUT, "testing.png"), bbox_inches="tight",
            pad_inches=0.02)
plt.close(fig)

print("figures written to", OUT)
