"""Generate the figures used in zorp-paper.md.

Re-run with `python3 make_figures.py` from this directory whenever the
architecture or test counts change. Every figure is built from real repo
state (crate layout, spec text, `cargo test` output), not illustrative
mockups. Colors match zorp-landing's actual palette
(zorp-landing/src/styles/tokens.css: light theme, navy foreground,
electric-blue accent), not an assumed dark/purple theme.

figures/logo.png is NOT generated by this script -- it's the real zorp
mark (a node-and-edge "Z"), placed here directly. Don't overwrite it.
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Circle
import os

OUT = os.path.join(os.path.dirname(__file__), "figures")
os.makedirs(OUT, exist_ok=True)

# zorp-landing/src/styles/tokens.css
BG = "#ffffff"
FG = "#12182b"      # --z-fg (navy)
ACCENT = "#1450f5"  # --z-accent (electric blue)
TINT = "#8fb0fb"    # --z-tint
GRAY = "#5b6478"    # --z-muted
SURFACE = "#f6f8fb"  # --z-surface
BORDER = "#dde1e9"  # --z-border
GREEN = "#15803d"   # --z-signal-ok


def box(ax, x, y, w, h, text, fc=SURFACE, ec=ACCENT, fontsize=10, textcolor=FG, lw=1.6):
    p = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.02,rounding_size=0.08",
        fc=fc, ec=ec, lw=lw, mutation_aspect=1,
    )
    ax.add_patch(p)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
             color=textcolor, fontsize=fontsize, fontweight="normal")
    return p


# ---------------------------------------------------------------------------
# Figure 1: layered architecture (from docs/superpowers/specs/
# 2026-08-09-zorp-architecture-design.md, "Structure" section).
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(6.4, 4.6), dpi=300)
fig.patch.set_facecolor("white")
ax.set_xlim(0, 10)
ax.set_ylim(0, 10)
ax.axis("off")

box(ax, 0.5, 8.0, 9.0, 1.4, "zorp-agent (one binary, one CLI)",
    fc=FG, ec=ACCENT, textcolor="#ffffff", fontsize=12)

caps = ["validate", "investigate", "co-write", "deliver"]
cw = 2.1
for i, c in enumerate(caps):
    box(ax, 0.5 + i * (cw + 0.1), 6.1, cw, 1.3, c, fc=SURFACE, ec=ACCENT, fontsize=10.5)

box(ax, 0.5, 4.1, 9.0, 1.5,
    "zorp-track (foundation, feature-gated)\ntracks · DuckDB run record · LanceDB · checkpoints",
    fc=SURFACE, ec=TINT, fontsize=10)

box(ax, 0.5, 2.1, 9.0, 1.5,
    "existing zorp-agent harness\ntools · sandbox · trust · verify · sessions · MCP",
    fc=SURFACE, ec=BORDER, fontsize=10)

box(ax, 0.5, 0.3, 9.0, 1.3,
    "zorp core crate (src/): model transport, raw primitives\n(binary: zorp)",
    fc=SURFACE, ec=BORDER, fontsize=10)

for y0, y1 in [(8.0, 7.4), (6.1, 5.6), (4.1, 3.6), (2.1, 1.6)]:
    ax.annotate("", xy=(5, y1), xytext=(5, y0),
                arrowprops=dict(arrowstyle="-|>", color=GRAY, lw=1.2))

fig.savefig(os.path.join(OUT, "architecture.png"), bbox_inches="tight", pad_inches=0.15)
plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 2: the four capabilities as a checkpointed pipeline (from
# docs/ARCHITECTURE.md and the per-capability specs). Each capability is
# also usable standalone -- shown as the dashed entry arrows.
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(7.4, 4.0), dpi=300)
fig.patch.set_facecolor("white")
ax.set_xlim(0, 12.4)
ax.set_ylim(0, 4.3)
ax.axis("off")

stages = [
    ("validate", "novelty +\nfeasibility read\n(needs a\nsearch MCP tool)"),
    ("investigate", "staged, pre-\nregistered attempts;\nevery one recorded"),
    ("co-write", "drafts from the\nrecorded evidence;\nhuman is author\nof record"),
    ("deliver", "matches draft to\nreal venues\n(needs huiban\nMCP tool)"),
]
n = len(stages)
w, h = 2.5, 1.8
gap = 0.55
x0 = 0.4
y0 = 1.1

for i, (name, desc) in enumerate(stages):
    x = x0 + i * (w + gap)
    box(ax, x, y0, w, h, f"{name}\n\n{desc}", fc=SURFACE, ec=ACCENT, fontsize=8.3)
    cx = x + w / 2
    ax.add_patch(Circle((cx, y0 + h + 0.35), 0.16, fc=GREEN, ec="none"))
    ax.text(cx, y0 + h + 0.35, "✓", ha="center", va="center", fontsize=8, color="white")
    ax.text(cx, y0 - 0.32, "runs\nstandalone", ha="center", va="top", fontsize=6.6, color=GRAY)
    ax.annotate("", xy=(cx, y0 - 0.02), xytext=(cx, y0 - 0.42),
                arrowprops=dict(arrowstyle="-|>", color=GRAY, lw=0.9, linestyle="dashed"))
    if i < n - 1:
        xn = x0 + (i + 1) * (w + gap)
        ax.annotate("", xy=(xn, y0 + h / 2), xytext=(x + w, y0 + h / 2),
                    arrowprops=dict(arrowstyle="-|>", color=ACCENT, lw=1.4))

ax.text(6.2, 3.85, "human checkpoint after each stage\n(interactive by default, --yes for unattended)",
        ha="center", va="bottom", fontsize=7.6, color=GRAY, style="italic")

ax.set_ylim(0, 4.3)
fig.savefig(os.path.join(OUT, "pipeline.png"), bbox_inches="tight", pad_inches=0.15)
plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 3: test counts per crate, from actual `cargo test -p <crate>` runs
# (default features) plus `cargo test -p zorp-agent --features research`,
# on 2026-08-13, HEAD fd07e81. `cargo test --workspace` (all crates,
# default features) totals 538 passing.
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(6.4, 3.4), dpi=300)
fig.patch.set_facecolor("white")

crates = ["zorp\n(core)", "zorp-mcp", "zorp-eval", "zorp-track", "zorp-agent\n(default)", "zorp-agent\n(+research)"]
counts = [24, 23, 41, 69, 381, 445]
colors = [TINT, TINT, TINT, TINT, ACCENT, ACCENT]

bars = ax.bar(crates, counts, color=colors, edgecolor=FG, linewidth=1.2)
for b, c in zip(bars, counts):
    ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 8, str(c),
            ha="center", va="bottom", fontsize=9, color=FG)

ax.set_ylabel("passing tests", color=FG)
ax.set_title("Test count by crate/feature set, cargo test, 2026-08-13", fontsize=10, color=FG)
ax.tick_params(colors=FG)
ax.spines[["top", "right"]].set_visible(False)
ax.spines[["left", "bottom"]].set_color(BORDER)
ax.set_ylim(0, max(counts) * 1.18)

fig.savefig(os.path.join(OUT, "testing.png"), bbox_inches="tight", pad_inches=0.15)
plt.close(fig)

print("figures written to", OUT)
